### ISSUE TITLE
Setting up server

### ISSUE THREAD

**Issue by cboydstun** [AjayKadoula/Laravel_Educational_Management_Application#3]
I run `php artisan migrate` per the instructions and receive the error: 

`Illuminate\Database\QueryException  : SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO) (SQL: select * from information_schema.tables where table_schema = forge and table_name = migrations)`

**Comment by AjayKadoula** [comment]
Please set your .env environment
